config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "home#index"
    get '/about', to: 'pages#about'
    get '/contact', to: 'pages#contact'
    resources :pageants
    resources :contestants
    resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contestant.rb
class Contestant < ApplicationRecord
    belongs_to :pageant
    validates   :pageant_id, presence: true
end

app/models/pageant.rb
class Pageant < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :pageant_name, presence: true, length: { minimum: 5, maximum: 30 }
    validates :pageant_description, presence: true, length: { minimum: 5, maximum: 150 }
    validates :pageant_category, presence: true, length: { minimum: 5, maximum: 30 }
    #validates_inclusion_of :time_zone, in: ActiveSupport::TimeZone.all(&:to_s)
    
    
    default_scope -> {order(updated_at: :desc)}
    belongs_to :user
    has_many :contestants, dependent: :destroy
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :pageants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
    
     before_action :set_contestant, only: [:show, :edit, :update, :delete]
    
    def index
        @contestants = Contestant.all
    end
    
    def new
        @contestant = Contestant.new
    end
    
    def create
        @contestant = Contestant.new(contestant_params)
        if @contestant.save
            #session[:chef_id] = @chef.id
            flash[:success] = "Welcome #{@chef.chefname} to Myrecipes App!"
            redirect_to contestant_path(@contestant)   
        else
            render 'new'
        end
    end
    
    def show
        #@chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 3)
    end
    
    def edit
        
    end
    
    def update
        if @contestant.update(contestant_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to @contestant
        else
            render 'edit'
        end
    end
    
    def destroy
        @contestant.destroy
        flash[:danger] = "chef and all associated recipes have been deleted"
        redirect_to contestants_path
    end
    
    private
    
        def contestant_params
            params.require(:contestant).permit(:con_num, :name, :profile, :image)
        end
        
    
        def set_contestant
            @contestant = Contestant.find(params[:id])
        end
    
        def require_same_user
            if current_chef != @chef
                flash[:danger] = "You can only delete your own account"
                redirect_to chefs_path
            end
        end
    end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pageants_controller.rb
class PageantsController < ApplicationController
  before_action :set_pageant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /pageants
  # GET /pageants.json
  def index
    @pageants = Pageant.all
  end

  # GET /pageants/new
  def new
    @pageant = Pageant.new 
  end
  
  def create
    @pageant = Pageant.new(pageant_params)
      @pageant.user = current_user
      if @pageant.save
        flash[:success] = "Pageant was created successfully"
        redirect_to pageant_path(@pageant)
      else
        render 'new'
      end
    end
  # GET /pageants/1
  # GET /pageants/1.json
  def show
  end

  # GET /pageants/1/edit
  def edit
  end

  
  # PATCH/PUT /pageants/1
  # PATCH/PUT /pageants/1.json
  def update
    respond_to do |format|
      if @pageant.update(pageant_params)
        format.html { redirect_to @pageant, notice: 'Pageant was successfully updated.' }
        format.json { render :show, status: :ok, location: @pageant }
      else
        format.html { render :edit }
        format.json { render json: @pageant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pageants/1
  # DELETE /pageants/1.json
  def destroy
    @pageant.destroy
        flash[:danger] = "Pageant and all associated contestants have been deleted"
        redirect_to pageants_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pageant
      @pageant = Pageant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pageant_params
      #params.fetch(:pageant, {})
      
      params.require(:pageant).permit(:pageant_name, :pageant_description, :pageant_category, :time_zone, :image, :startdate, :enddate, :user_id)
      
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def contact
    end
    
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contestant_helper.rb
module ContestantHelper
end

app/helpers/contestants_helper.rb
module ContestantsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pageants_helper.rb
module PageantsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contestants/_form.html.erb
<%= render 'shared/errors', obj: @contestant  %>

<div class="row">
    <div class="col-md-12">
        <%= form_for(contestant, :html => { class: "form-horizontal", multipart: true, role: "form" }) do |f| %>
    <div class="form-group">
        <div class="control-label col-md-2">
            <%= f.label :Number %>
            </div>
            <div class="col-md-8">
                <%= f.text_field :con_num, class: "form-control", placeholder: "Contestant's Number", autofocus: true %>
            </div>
            </div>
        <div class="form-group">
        <div class="control-label col-md-2">
            <%= f.label :Name %>
            </div>
            <div class="col-md-8">
                <%= f.text_field :name, class: "form-control", placeholder: "Contestant's Name" %>
            </div>
            </div>
            <div class="form-group">
        <div class="control-label col-md-2">
            <%= f.label :Profile %>
            </div>
            <div class="col-md-8">
                <%= f.text_field :profile, rows:5, class: "form-control", placeholder: "Contestant's Profile" %>
            </div>
            </div>
            
            <div class="form-group">
              <div class="control-label col-md-2">
                <%= f.label :image, "Add an Image" %>
              </div>
              <div class="col-md-8">
                <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
              </div>
                </div>
            
        <div form-group>
          <div class="col-md-offset-2 col-md-10">
              <%=  f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
          </div>  
        </div>
        <% end %>
        <div class="col-md-4 col-md-offset-4 colormatch">
            [<%= link_to "Return to pageants listing", pageants_path %>]
        </div>
</div>
</div>

app/views/contestants/index.html.erb
<h1 align="center">Contestants Index</h1><hr/>

app/views/contestants/new.html.erb
<h2 class="col-md-9" align="center">Create a contestant</h2>
<div class="col-md-9">
<%= render 'form', contestant: @contestant %>
</div>

<!--Side content-->
<div class="col-md-3">
 something
 
</div>

app/views/home/index.html.erb
 <div class="jumbotron center">
       <h1 align="center">welcome to ezyvote</h1>  
      <!-- <h2 align="center">The best Pageant Voting app</h2>-->
       <p><%= link_to "login with facebook", "#", class: "btn btn-danger btn-lg btn-xlarge center" %></p>
    </div>
    
  <!--<div class="thumbnail right-caption span4">
  <img src="http://placehold.it/120x160" alt="">
  <div class="caption">
    <h5>Thumbnail label</h5>
    <p>Cras justo odio, dapibus ac facilisis in, egestas eget. Eget metus</p>
    <p><a href="#" class="btn btn-primary">Action</a> <a href="#" class="btn">Action</a></p>
  </div>
</div>-->

          
        <!--</div>-->
      </div>
      

      <div class="row">
      <div class="col-xs-12 col-sm-4">Pageant information goes here as a link after they are created</div>
      <div class="col-xs-12 col-sm-4">Pageant information goes here as a link after they are created</div>
      <!-- Optional: clear the XS cols if their content doesn't match in height-->
  <div class="clearfix visible-xs-block"></div>
  <div class="col-xs-12 col-sm-4">Pageant information goes here as a link after they are created</div>
  </div>

app/views/layouts/_footer.html.erb
<div id="footer">
      <!--	<div class="row">
          <ul class="list-unstyled">
            <li class="col-md-3 col-sm-4 col-xs-6">
              <a href="index.html">Home</a>
            </li>
            <li class="col-md-3 col-sm-4 col-xs-6">
              <a href="services.html">Services</a>
            </li>
            <li class="col-md-3 col-sm-4 col-xs-6">
              <a href="404.html">Studies</a>
            </li>
          </ul>
		</div><!--/row-->
</div>

app/views/layouts/_messages.html.erb
<dic class="row">
<div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>">
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
    </div>
        <% end %>
    </div>
</div>

app/views/layouts/_nav.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    
   
<!-- Fixed navbar 

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->

<nav class="navbar navbar-default navbar-fixed-top" >
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ezyvote", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path, class: "links" %></li>
            <li><%= link_to "Contestants", pageants_path, class: "links" %></li>
            <li><%= link_to "Create Vote", new_pageant_path, class: "links" %></li>
            <li><%= link_to "About", about_path, class: "links"%></li>
            <li><%= link_to "Contact", contact_path, class: "links" %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          
          <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'links' %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'links' %></li>
          
            <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'links' %></li>
          <li><%= link_to "Login", new_user_session_path, :class => 'links' %></li>
          
          <% end %>
        
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ezyvote</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/nav' %>
      
      <div class="container1"><%=  render 'layouts/messages' %></div>
      <div class="container">
    <%= yield %>
    </div>
    <!--Here was footer, now he is gone-->
    <div>
    <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/pageants/_form.html.erb
<%= render 'shared/errors', obj: @pageant  %>

<div class="row">
    <div class="col-md-12">
        <%= form_for(@pageant, :html => { class: "form-horizontal", multipart: true, role: "form" }) do |f| %>
    <div class="form-group">
        <div class="control-label col-md-2">
            <%= f.label :pageant_name %>
            </div>
            <div class="col-md-8">
                <%= f.text_field :pageant_name, class: "form-control", placeholder: "Name of Pageant", autofocus: true %>
            </div>
            </div>
        <div class="form-group">
        <div class="control-label col-md-2">
            <%= f.label :description %>
            </div>
            <div class="col-md-8">
                <%= f.text_area :pageant_description, rows:3, class: "form-control", placeholder: "Description of Pageant" %>
            </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :category %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :pageant_category, rows:10, class: "form-control", placeholder: "Give a category of your choice" %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :StartDate, "Start Date" %>
                </div>
                <div class="col-md-8">
                    <%= f.date_field :startdate, class: "form-control", placeholder: "Enter the start date" %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :Enddate, "End Date" %>
                </div>
                <div class="col-md-8">
                    <%= f.date_field :enddate, class: "form-control", placeholder: "Enter the end date" %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :time_zone %>
                </div>
                <div class="col-md-8">
                    <%= f.time_zone_select :time_zone, nil, {}, class: 'form-control' %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :image, "Add Banner" %>
                </div>
                <div class="col-md-8">
                    <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
                </div>
            </div>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <div form-group>
                <div class="col-md-offset-2 col-md-10">
                      <%=  f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
                </div>  
            </div>
                        <% end %>
            <div class="col-md-4 col-md-offset-4 colormatch">
                    [<%= link_to "Return to pageants listing", pageants_path %>]
            </div>
</div>
</div>

app/views/pageants/edit.html.erb
<h1 align="center">Editing Pageant</h1><hr/>

<%= render 'form', pageant: @pageant %>

app/views/pageants/index.html.erb
<!--<p id="notice"></p>-->
<h2 align="center">Contestants</h2><hr/>

<% @pageants.each do |pageant| %>
      <div class="col-sm-6 col-md-3">
        <div class="=thumbnail thumb-box">
          <h3 class="triad"><%= link_to pageant.pageant_name, pageant_path(pageant) %></h3>
          <%= image_tag( pageant.image, size: "180x180" ) %>
        </div>
      </div>
      <% end %>
    

app/views/pageants/new.html.erb
<h2 class="col-md-9" align="center">Create Vote</h2>
<div class="col-md-9">
<%= render 'form', pageant: @pageant %>
</div>



<!--Side content-->
<div class="col-md-3">
 something
 
</div>

app/views/pageants/show.html.erb
<div align="center">
    
      </div>
    
    <div>

  <div class="row">
				<div class="col-md-8" >
				    <!--
				    <div class="panel panel-default">
            <div class="panel-body">
             
            </div>
          </div>
				    -->
         <%= image_tag @pageant.image.url, class: "img-responsive center-block" if @pageant.image? %>
         
  <!--Here goes the trial code for tabs-->
  <div class="container col-md-8">
  <h2 align="center">Pageants Created</h2>
  <p>Menu</p>

  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">Vote Created</a></li>
    <li><a data-toggle="tab" href="#menu1">Add Contestants</a></li>
    <!--<li><a data-toggle="tab" href="#menu2">Edit Vote</a></li>-->
    <li><a data-toggle="tab" href="#menu2">Edit Vote</a></li>
    <!--<li><a data-toggle="tab" href="#menu3">Delete Vote</a></li>-->
    <%  if user_signed_in? %>
    <li><a data-toggle="tab" href="#menu3"><%= link_to "Delete", pageant_path(@pageant), method: :delete,
                                data: {confirm: "Are you sure ?" } %></a></li><%  end %>
  </ul>

  <div class="tab-content">
      <h3 align="center"><b>Vote Created</b></h3>
    <div class="tab-pane active fade in active" id="home">
          <h4 align="center"><%= @pageant.pageant_name %></h4>
          <h4 align="center"><%= @pageant.pageant_description  %></h4>
          <h4 align="center"><%= @pageant.pageant_category  %></h4>
          <h4 align="center">Starting: <%= @pageant.startdate.to_s %></h4>
          <h4 align="center">  Ending: <%= @pageant.enddate.to_s %></h4>
          <h4 align="center">Time Zone: <%= @pageant.time_zone  %></h4>
		</div>
		<%  if @pageant.user == current_user %>
    <div id="menu1" class="tab-pane fade">
      <p><%=  render 'form', contestant: @contestant %></p>
    </div>
    <div id="menu2" class="tab-pane fade">
      
      <p><%= render 'form', pageant: @pageant %></p>
    </div><% end %>
    <div id="menu3" class="tab-pane fade">
      <h3>Delete</h3>
      <p>Delete the Votes or Contestants created from here.</p>
    </div>
  </div>
</div>

  
  <!--It ends here-->
        
  <!--<div id="exTab2" class="container">	
  <ul class="nav nav-tabs">
			<li class="active">
        <!--<a  href="#1" data-toggle="tab">--><!--<%= link_to 'Edit', edit_pageant_path(@pageant) %>--><!--</a>-->
			<!--</li>-->
		<!--	<li ><a href="#tab_b" data-toggle="tab">Add Contestant</a></li>-->
			<!--<li><a href="#3" data-toggle="tab">Delete Pageant</a></li>-->
			<!--<li><%= link_to "Delete", pageant_path(@pageant), method: :delete,
                                data: {confirm: "Are you sure ?" } %></li>-->
		<!--</ul>-->

			<div class="tab-content ">
			  <!--<div class="tab-pane active" id="1">
          <h4 align="center"><%= @pageant.pageant_name %></h4>
          <h4 align="center"><%= @pageant.pageant_description  %></h4>
          <h4 align="center"><%= @pageant.pageant_category  %></h4>
          <h4 align="center">Starting: <%= @pageant.startdate.to_s %></h4>
          <h4 align="center">  Ending: <%= @pageant.enddate.to_s %></h4>
          <h4 align="center">Time Zone: <%= @pageant.time_zone  %></h4>
				</div-->
				<!--<div class="tab-pane" id="2">
          <h3>Notice the gap between the content and tab after applying a background color</h3>
				</div>
        <div class="tab-pane" id="3">
          <h3>add clearfix to tab-content (see the css)</h3>
				</div>-->
			</div>
  </div>

        </div>
        <div class="panel-heading center">Current Pageants</div>
        <div class="col-md-4">
          <!--Current created pageants appear here-->
        </div>
        </div>
       
					
      
 |
<%= link_to 'Back', pageants_path %>
<% render "layouts/footer"%>
</body>
</html>

app/views/pages/about.html.erb
<div class="row">
<div class="col-md-8">
<div class="panel panel-default">
  <div class="panel-heading"><h2 align="center">About ezyvote </h2></div>
  <div class="panel-body">
    For Questions and Inquiry, please send mail to <b><i>inquiry@ezyvote.com</i></b>. We will respond to you as soon
    as possible, we value your response to us.
    <p>
        For any query about Premium voting, please send it to <i><b>sales@ezyvote.com</b></i>. We will be able to respond</br>
        to you to answer your questions.
        
    </p>
  </div>
</div>
</div>
<!--Side content goes here-->
<div class="col-m-4 panel-body">
 <h3 align="center">Current Pageants</h3>
</div>
</div>

app/views/pages/contact.html.erb
<div class="row">
<div class="col-md-8">
<div class="panel panel-default">
  <div class="panel-heading"><h2 align="center">Contact us </h2></div>
  <div class="panel-body">
    For Questions and Inquiry, please send mail to <b>inquiry@ezyvote.com</b>. We will respond to you as soon
    as possible, we value your response to us.
    <p>
        For any query about Premium voting, please send it to <b>sales@ezyvote.com</b>. We will be able to respond</br>
        to you to answer your questions.
        
    </p>
  </div>
</div>
</div>
<!--Side content goes here-->
<div class="col-m-4">
 <h3 align="center">Current Pageants</h3>
</div>
</div>

app/views/pages/createpageant.html.erb
<%= form_with(model: pageant, local: true) do |form| %>
  <% if pageant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pageant.errors.count, "error") %> prohibited this pageant from being saved:</h2>
      
      <div class="message">
      <ul>
      <% pageant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shared/_errors.html.erb
 <% if obj.errors.any? %>
 <div class="row">
     <div class="col-md-8 col-md-offset-2">
         <div class="panel panel-danger">
             <div class="panel-heading">
             <h2 class="panel-title">
                 <%= pluralize(obj.errors.count, "error") %>
                 prohibited this <%= obj.class %> from being saved:
             </h2>
             <div class="panel-body">
                 <ul>
                     <% obj.errors.full_messages.each do |msg| %>
                 <li><%= msg %></li>
                     <% end %>
                 </ul>
             </div>
             </div>
         </div>
     </div>
 </div>
 <% end %>